### ISSUE TITLE
Reuse CodeQL, Format Checker, and Static Analysis Workflows

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [nasa/osal#1188]
**Is your feature request related to a problem? Please describe.**
When needing to change workflows, one must create an issue and PR for each submodule. This feature would reduce duplication.

**Describe the solution you'd like**
To reuse workflows, the workflow simply uses `uses` and the full path of the workflow. The cFS workflows, or targeted workflows, must include workflow_call and runs-on as seen below. 
```
on:
  push:
  pull_request:
  workflow_call:
    inputs:
      runs-on: 
        description: Platform to execute on
        type: string
        default: ubuntu-latest
```

**Describe alternatives you've considered**
Keep it as is. 

**Additional context**
Tested in forked cFS: https://github.com/ArielSAdamsNASA/cFS-JSF-Rules/actions/runs/1381659167
Tested in forked OSAL: https://github.com/ArielSAdamsNASA/osal/actions/runs/1381486439

**Requester Info**
Ariel Adams, ASRC Federal
