### ISSUE TITLE
Show CodeQL Preview

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [nasa/osal#986]
**Is your feature request related to a problem? Please describe.**
Code preview is not available for code scanning results from CodeQL. 

**Describe the solution you'd like**
The preview is available when the osal submodule is checked out rather than the cFS bundle. I have not found a way to checkout just the submodule AND use the tests. 

Currently, the workflow checks out the cFS bundle. 
```
    steps:
      - name: Checkout bundle
        uses: actions/checkout@v2
        with:
          repository: nasa/cFS
          submodules: true

      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          path: osal
```
To show the preview, only the osal submodule needs to be checked out:
```
      - name: Checkout submodule
        uses: actions/checkout@v2
```

**Describe alternatives you've considered**
Would like to keep the tests, but believe they require the cFS bundle. 

**Additional context**
Community Support Thread: https://github.community/t/codeql-with-submodules/159839/10
> The reason is that we currently don’t look for files across submodules for the preview.

**Requester Info**
Ariel Adams, ASRC Federal
